# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazypkg < Formula
  desc ""
  homepage ""
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/ymtdzzz/lazypkg/releases/download/v0.0.5/lazypkg_Darwin_x86_64.tar.gz"
      sha256 "81cca1b23bcdc6c2472e253adbe6f3485077437a5d14476ec806d0322bd29766"

      def install
        bin.install "lazypkg"
      end
    end
    on_arm do
      url "https://github.com/ymtdzzz/lazypkg/releases/download/v0.0.5/lazypkg_Darwin_arm64.tar.gz"
      sha256 "cc4d3c01f1de8c716b00f89d5ce00ddd0b8f0a7a9bbcb6cfc1de8d088f65d7da"

      def install
        bin.install "lazypkg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ymtdzzz/lazypkg/releases/download/v0.0.5/lazypkg_Linux_x86_64.tar.gz"
        sha256 "eab5197a63bdf16c82e910005b5256e03bfa511de3e04f0a7ba4d5de5d7df603"

        def install
          bin.install "lazypkg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ymtdzzz/lazypkg/releases/download/v0.0.5/lazypkg_Linux_arm64.tar.gz"
        sha256 "60dbbfac0d65536bdb70b52fd3e6ea0174b34fa2593079b4416df6e77252fca1"

        def install
          bin.install "lazypkg"
        end
      end
    end
  end
end
