# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OtelTui < Formula
  desc ""
  homepage ""
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/ymtdzzz/otel-tui/releases/download/v0.0.2/otel-tui_Darwin_x86_64.tar.gz"
      sha256 "9e668dbcfdb7a9c495203fb10792c1bf31142a7a629e8c803f9efdfffbc9bb98"

      def install
        bin.install "otel-tui"
      end
    end
    on_arm do
      url "https://github.com/ymtdzzz/otel-tui/releases/download/v0.0.2/otel-tui_Darwin_arm64.tar.gz"
      sha256 "518703fc10c048c48fa5a9e219002d410f29c0b7f70d429897dbfb2c77e416ed"

      def install
        bin.install "otel-tui"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ymtdzzz/otel-tui/releases/download/v0.0.2/otel-tui_Linux_x86_64.tar.gz"
        sha256 "24e5f4c544add9489751811ac93a76e310b761ce656cdc13aae8ddac1741bec8"

        def install
          bin.install "otel-tui"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ymtdzzz/otel-tui/releases/download/v0.0.2/otel-tui_Linux_arm64.tar.gz"
        sha256 "83e88dd6c9b677c8101635f3932050844932ff1d92024f70e913d47d2cc1346c"

        def install
          bin.install "otel-tui"
        end
      end
    end
  end
end
